@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction
title US021 - Domain Model
skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class GSM {

}
class ToDoList {

}

class Task{
    type
    duration
}

GSM "1" -- "*" ToDoList : Add new entry
ToDoList "1" -- "*" Task : contains

@enduml