@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title US008 - Domain Model

class Organization {
    name
    nif
    website
    phoneNumber
    email
}

class Vehicle{
    plateId
    brand
    model
    type
    tare
    grossWeight
    currentKm
    registerDate
    acquisitionDate
    checkupFrequencyKms
}




FM "1" -- "*" Vehicle : "lists needing check-up >"
Organization "1" -- "*" Vehicle : "owns >"




@enduml