@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US002 - System Sequence Diagram (SSD)

autonumber

actor "HRM" as Employee
participant ":RegisterJobUI" as CJU
participant ":RegisterJobController" as CJC
participant ":Repositories" as REPO
participant "repositories\n:Repositories" as Repos
participant "jobRepository\n:JobRepository" as ORG
participant ":Job" as JOB

activate Employee

    Employee -> CJU : Asks to register a new job
    activate CJU

        CJU --> Employee : Requests job data (job name)
    deactivate CJU
    loop until typed data is validated
    Employee -> CJU : Types requested data
    activate CJU
    CJU --> CJU : keepData(jobName)

        CJU --> Employee : Shows typed data and requests confirmation
    deactivate CJU
    end

    Employee -> CJU : Confirms data and submits
    activate CJU

    CJU -> CJC : createJob(jobName)
    activate CJC

    CJC -> REPO : getInstance()
    activate REPO

    REPO --> CJC : repositories
    deactivate REPO

    CJC -> Repos : getJobRepository()
    activate Repos

    Repos --> CJC : jobRepository
    deactivate Repos

    CJC -> ORG : createJob(jobName)

    activate ORG

    ORG -> JOB** : createJob(jobName)

    ORG --> ORG : addToJobList(jobName)

    ORG --> ORG : validateJob(jobName)

    ORG --> CJC : operation success
    deactivate ORG
    CJC --> CJU : operation success
    deactivate CJC

        CJU --> Employee : Displays operation success and shows the \nlist of all registered jobs
    deactivate CJU

@enduml