@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto
title US002 - Class Diagram
skinparam classAttributeIconSize 0


'left to right direction

Class RegisterJobController{
    +getJob()
    +registerJob(jobName)
}

Class RegisterJobUI {

}

class Organization {
    -String name
    -NIF nif
    -Website
    -Phonenumber
    -Email email
}

class HRM {

}

class Job{
    -ListOfAllRegisteredJobs

}
RegisterJobUI --.> RegisterJobController
HRM --o Organization
RegisterJobController --.> Job
HRM -->  RegisterJobUI
@enduml
