@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto
title US002 - Class Diagram
skinparam classAttributeIconSize 0


'left to right direction

Class RegisterJobController{


    + RegisterJobController()
    + RegisterJobController(jobRepository)
    - getJobRepository()
    + registerJob(jobName)
}

Class RegisterJobUI {
    - String jobName;

    + RegisterJobUI()
    + getController()
    + run()
    - submitData()
    - requestData()
    - requestJobName()
    - validateJob(jobName)

}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getJobRepository()
}

class jobRepository{
    - List<Job> jobList

    + JobRepository()
    - add(job)
    - validateJob(job)
    + registerJob(jobName)
}

class Job{
    - String jobName

    + Job(jobName)
    + getJobName()
    + setJobName(jobName)
    + clone()
    - validateJob(jobName)

}

Repositories --> Repositories : "instance"
Repositories --> "1" jobRepository
RegisterJobUI ..> RegisterJobController
RegisterJobController ..> Repositories : repositories
jobRepository "1" --> "*" Job : "job"
RegisterJobController ..> jobRepository : jobRepository

@enduml
