@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto
title US002 - Class Diagram
skinparam classAttributeIconSize 0


'left to right direction

Class RegisterJobController{
    +createJob()
}

Class RegisterJobUI {

}

class Repositories {
    +getInstance()
    +getJobRepository()
}

class jobRepository{
    +createJob(String jobName)
}

class Job{
    -jobName
    +Job(jobName)
}

Repositories --> Repositories : "instance"
Repositories --> "1" jobRepository
RegisterJobUI ..> RegisterJobController
RegisterJobController ..> Repositories : repositories
jobRepository ..> Job : "Job"

@enduml
