@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "FM\nMS Employee" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to create a new vehicle
    activate System

        System --> Employee : shows brand, model and type list and asks to select fields
    deactivate System


    Employee -> System : selects a brand, model and type
    activate System

        System --> Employee : requests other data ( tare, gross weight, current km, register date, acquisition date, maintenance/checkup frequency (in kms))
    deactivate System

    Employee -> System : types in the requested data
    activate System

        System --> Employee : shows all data and requests confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml