@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Fleet Manager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to create a new task
    activate System

        System --> Employee : requests data (brand, model, plate number)
    deactivate System

    Employee -> System : types requested data
    activate System

        System --> Employee : shows the list of vehicles needing the checkup
    deactivate System

    Employee -> System : selects a vehicle
    activate System

        System --> Employee : shows all data about that vehicle
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml