@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US008 - System Sequence Diagram (SSD)

autonumber

actor "Fleet Manager" as Employee
participant ":NeedCheckupUI" as System

activate Employee

    Employee -> System : Requests to show the list of vehicles needing inspection
    activate System

        System -> System : Determine vehicles that needs inspection \nbased on the formulas/criteria and gather \ndetails of those vehicles.

        System -> Employee : Shows the list of vehicles needing check-up with \nvehicle details and the data used.

    deactivate System

note right
**(3) NOTE:**
* **Vehicle details:**
Plate, brand, model, last check-up

* **Data used to generate the list:**
Current kilometers, check-up frequency
last check-up done
end note

    deactivate System

@enduml