@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US008 - System Sequence Diagram (SSD)

autonumber

actor "Fleet Manager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : Requests to show the list of vehicles needing inspection
    activate System

        System -> System : Determine vehicles needing inspection \nand gather details of each vehicle.

        System -> Employee : Show the list of vehicles needing check-up with vehicle \ndetails and the data/inputs used on the formula

    deactivate System

note right
**Vehicle details:**
*Plate, brand, model, last check-up

**Data/Inputs used to determine vehicles:**
*current kilometers, check-up frequency
last check-up done
end note

    deactivate System

@enduml