@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title US029 - Domain Model

class Agenda{
    tasks
}

class Task{
    title
    description
    state
    urgency
    assignedGreenSpace
    assignedVehicle
    assignedTeam
    startDate
    expectedDuration
}

class Collaborator{
    name
    admissionDate
    birthDate
    phoneNumber
    email
    idDocType
    idDocNumber
}


Task "*" -u- "1" Agenda : "are part of >"
Collaborator -right- Task : "mark as complete >"
@enduml