    @startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US001 - System Sequence Diagram (SSD)

autonumber

actor "HRM" as Employee
participant ":RegisterSkillUI" as System

activate Employee

    Employee -> System : Asks to register a new skill
    activate System

        System --> Employee : Requests data (skill name)
    deactivate System
    loop until typed data is validated
    Employee -> System : Types requested data
    activate System
        System --> System : validatesData
        System --> Employee : Shows typed data and requests confirmation
    deactivate System
end
    Employee -> System : Confirms data and submits
    activate System
        System --> System : keepsData(skillName)
        System --> Employee : Displays operation success
    deactivate System

@enduml