@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US004 - System Sequence Diagram (SSD)

autonumber

actor "HRM" as Employee
participant ":AssignSkillUI" as System

activate Employee

    Employee -> System : Asks to assign one or more skills to a collaborator
    activate System

        System --> Employee : Shows a list of Collaborators and asks to select one
    deactivate System

    Employee -> System : Selects a collaborator

    loop

    activate System

        System --> Employee : Displays a list of available skills.
    deactivate System

    Employee -> System : Selects option


    activate System
    end

        System --> Employee : Shows all data and requests confirmation
    deactivate System

    Employee -> System : Confirms the operation
    activate System

        System --> Employee : Displays operation success
    deactivate System

@enduml