@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction
Class Organization {
    -String name
    -NIF nif
    -Website website
    -Phonenumber phoneNumber
    -Email email
    +getVehiclesNeedingCheckup()
}

Class ListVehiclesNeedingCheckupController{
    -List<Vehicle> vehiclesNeedingCheckupList
    +getVehiclesNeedingCheckup()
}

Class ListVehiclesNeedingCheckupUI{

}

ListVehiclesNeedingCheckupUI --.> ListVehiclesNeedingCheckupController
ListVehiclesNeedingCheckupController --o Organization

@enduml