@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US021 - System Sequence Diagram (SSD)

autonumber

actor "GSM" as GSM
participant ":AddNewEntryToDoUI" as UI





activate GSM

    GSM -> UI : Asks to add a new entry on To-Do List
    activate UI



    loop until doesn't select a valid option
                    UI --> GSM : Shows list of green spaces and asks to select one
                deactivate UI

                GSM -> UI : Selects a green space

                activate UI
                 UI --> UI: validates Selection
                |||
                end

            UI --> UI : keepData(greenspace)


    loop until typed data is validated

        UI --> GSM : Requests data (title, description, expected duration)
    deactivate UI

    GSM -> UI : Types requested data

    activate UI

    UI --> UI : validates typed data
    |||


    end


        UI --> UI : keepData(title, description, expectedDuration)
        note right of UI
            expectedDuration is composed
            by days, hours and minutes
            end note

        |||




    loop until doesn't select a valid option
                        UI --> GSM : Shows list of task taskType and urgency and asks to select one
                    deactivate UI

                    GSM -> UI : Selects type of task and urgency
                    note right
                    Task type and urgency are
                    both enumerate types
                    end note
                    activate UI
                     UI --> UI: validates Selection
                    |||
                    end

                UI --> UI : keepData(type, urgency)


        |||





                UI --> GSM : Shows all data and requests confirmation
deactivate UI
    GSM -> UI : Confirms data

    activate UI

    UI --> UI : adds the new task\nto the To-Do list


        UI --> GSM : Displays operation success
    deactivate UI

@enduml