@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Green Space\nManager" as GSM
participant ":registerGreenSpaceUI" as UI

activate GSM

    GSM -> UI : asks to create a new Green Space
    activate UI

        UI --> GSM : Displays the types of green spaces and asks\nto select one (garden, medium, large)
    deactivate UI

    GSM -> UI : selects type of green space
    activate UI
        UI --> UI : keepData(type)
loop until typed data is validated
        UI --> GSM : requests data (name, streetNumber,\npostalCode, city, district, totalArea)
    deactivate UI

    GSM -> UI : types requested data
    activate UI
end loop
        UI --> UI : keepData(name,streetNumber,\npostalCode,city,district,totalArea)
        UI --> GSM : shows all data and requests confirmation
    deactivate UI

    GSM -> UI : confirms data
    activate UI

        UI --> GSM : displays operation success
    deactivate GSM

@enduml