@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US020 - System Sequence Diagram (SSD)

autonumber

actor "Green Space\nManager" as GSM
participant ":RegisterGreenSpaceUI" as UI

activate GSM

    GSM -> UI : asks to create a new Green Space
    activate UI



loop until typed data is validated
        UI --> GSM : requests data (name, type, area, street,\n streetNumber, postalCode, city, district)
    deactivate UI

    GSM -> UI : types requested data

    activate UI
    UI --> UI: Validates input data
    |||
end loop
        UI --> UI : keepData(name, type, area, street,\n streetNumber,postalCode, city, district)
        UI --> GSM : shows all data and requests confirmation
    deactivate UI

    GSM -> UI : confirms data
    activate UI

        UI --> GSM : displays operation success
    deactivate GSM

@enduml