@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US008 - System Sequence Diagram (SSD)

autonumber

actor "Fleet Manager" as Employee
participant ":ListVehiclesNeedingCheckupUI" as UI
participant ":ListVehiclesNeedingCheckupController" as CTRL
participant ":Repositories" as Repos
participant "repositories\n:Repositories" as PLAT
participant "vehicleRepository" as VRepo
participant "checkupRepositoty\n:CheckupRepository" as CheckupRepo

    Employee -> UI : Requests to show the list of \nvehicles needing a check-up
    activate UI

        UI -> CTRL** : create
        UI -> CTRL : getVehiclesNeedingCheckup()
        activate CTRL

            CTRL -> Repos : getInstance()
            activate Repos

                Repos --> CTRL : repositories
            deactivate Repos
            CTRL -> PLAT : getVehicleRepository()
            activate PLAT

                PLAT --> CTRL : vehicleRepository
            deactivate PLAT

            CTRL-> VRepo : getVehiclesNeedingCheckup()
            activate VRepo

                VRepo --> VRepo : getVehicles()
                VRepo --> Repos : getInstance()
                activate Repos

                    Repos --> VRepo : repositories
                deactivate Repos
                VRepo -> PLAT : getCheckupRepository()
                activate PLAT

                    PLAT --> VRepo : checkupRepository
                deactivate PLAT
                loop for each vehicle in vehiclesList
                    VRepo --> VRepo : needsCheckup(Vehicle vehicle)
                    activate VRepo

                        VRepo -> CheckupRepo : getCheckup(vehicle)
                        activate CheckupRepo

                            CheckupRepo --> VRepo : kmsAtCheckup
                        deactivate CheckupRepo
                    VRepo --> VRepo : true/false
                    deactivate VRepo
                    VRepo --> VRepo : addVehicleToNeedCheckupList(vehicle)
                end loop
                VRepo -> CTRL : vehiclesNeedingCheckupList
            deactivate VRepo
            CTRL -> UI : vehiclesNeedingCheckupList
        deactivate CTRL

        UI -> Employee : Shows the list of vehicles needing check-up with \nvehicle details and the data used.

    deactivate UI

@enduml