@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US001 - Sequence Diagram

autonumber

'hide footbox
actor "HRM" as HRM
participant ":RegisterSkillUI" as RSU
participant ":RegisterSkillController" as RSC
participant ":organization \nOrganization" as ORG
participant ":Skill \nSkill" as Skill

activate HRM

        HRM -> RSU : Asks to register a skill

        activate RSU

            RSU --> HRM : Request data(skill name)
        deactivate RSU

        HRM -> RSU: Types requested data

        activate RSU
            RSU --> RSU : keepData(skill name)
            |||
            RSU -> RSC : getSkillList()


            activate RSC

                RSC -> ORG : getSkillList()
                |||

                activate ORG

                ORG --> RSC : SkillList
                deactivate ORG

                RSC --> RSU: SkillList
            deactivate RSC

            RSU --> HRM : Shows Skill list and asks to select one

        deactivate RSU

        HRM -> RSU : Selects a skill

        activate RSU

            RSU --> RSU : keepData(skill name)
            RSU --> HRM : Shows all data and requests confirmation
        deactivate RSU

        HRM -> RSU : Confirms data

        activate RSU

            RSU -> RSC : createSkill(name)
            activate RSC

                RSU -> ORG : createSkill(name)
                activate ORG

                    ORG -> Skill : createSkill(name)
                    note right of Skill : Skill constructor\n normally validates arguments.
                    |||
                    |||
                    ORG -> ORG : addToSkillList(skill)
                    ORG --> RSC : skill
                deactivate ORG

                RSC --> RSU : skill
            deactivate RSC

            RSU --> HRM : Displays operation sucess

        deactivate RSU



@enduml