@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto
skinparam classAttributeIconSize 0
'left to right direction

Repositories -> Repositories : instance


Repositories --> "1" SkillRepository

SkillRepository ..> Skill : createSkill(skillName)
RegisterSkillController ..> Repositories : repositories
RegisterSkillUI ..> RegisterSkillController

class RegisterSkillUI {

}

class RegisterSkillController {
    + getSkillRepository()
}

class Repositories {
    + getInstance()
    + getSkillRepository()
}

class SkillRepository {
    + getSkillList()
}

class Skill {
    + validateName(skillName)
}

@enduml