    @startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US001 - Sequence Diagram

autonumber

actor "HRM" as Employee
participant ":RegisterSkillUI" as System
participant ":RegisterSkillController" as RSC
participant ":Repository" as REP
participant ":repositories \nRepositories" as REPS
participant ":skillRepository \nSkillRepository" as SR

activate Employee

    Employee -> System : Asks to register a new skill
    activate System

        System --> Employee : Requests data (skill name)
    deactivate System
    loop until typed data is validated
    Employee -> System : Types requested data
    activate System
        System --> System : keepData(skillName)

        System --> Employee : Shows typed data and requests confirmation

    deactivate System
end
    Employee -> System : Confirms data and submits
    activate System
        System -> RSC : createSkill(skillName)
        activate RSC

                RSC -> REP : getInstance()

                activate REP
                REP --> RSC : repositories
                deactivate REP
                RSC -> REPS : getSkillRepository()

                activate REPS
                REPS --> RSC : skillRepository
                deactivate REPS

                RSC -> SR : createSkill(skillName)
                activate SR

                SR -> Skill** : createSkill(skillName)
                Skill --> Skill : validateName(skillName)

                SR --> SR : addToSkillList(skillName)
                SR --> SR : validate(skillName)
                SR --> RSC : operation success
                deactivate SR


            RSC --> System : operation success

        deactivate RSC


        System --> Employee : Displays operation success

@enduml