@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction
title US022 - Domain Model
skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class GSM {

}
class Agenda {

}

class Task{
    title
    description
    state
    urgency
    assignedGreenSpace
    assignedVehicle
    assignedTeam
    expectedDuration
}

GSM "1" -- "*" Task : "plans >"
Agenda "1" -- "*" Task : "enters in <"

@enduml