@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US007 - System Sequence Diagram (SSD)

autonumber

actor "Fleet Manager" as Employee
participant ":RegisterCheckupUI" as System

activate Employee

    Employee -> System : Asks to register a new vehicle's check-up
    activate System

        System --> Employee : Shows the list of vehicles and asks to select one
    deactivate System

    Employee -> System : Selects a vehicle
    activate System

        System --> Employee : Requests check-up data (Date of check-up, Current kilometers)
    deactivate System
    loop until data is validated
    Employee -> System : Types requested data
    activate System
        System --> System : validatesData
        System --> Employee : Shows all data and requests confirmation
    deactivate System

    end loop

    Employee -> System : Confirms data
    activate System
        System --> System : keepData(vehicle, date of \ncheck-up, current kilometers)
        System --> Employee : Displays operation success
    deactivate System

@enduml