@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US027 - System Sequence Diagram (SSD)

autonumber

actor "Green Space\nManager" as GSM
participant ":ListGreenSpacesUI" as UI

activate GSM

    GSM -> UI : asks to list all the green spaces managed by me
    activate UI

        UI --> UI : gets all the green spaces\nmanaged by the GSM logged in
        UI --> GSM : displays all the green spaces managed by the GSM
    deactivate UI

@enduml