@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0
Title US08 - Class Diagram

'left to right direction

Class ListVehiclesNeedingCheckupUI {
    -ListVehiclesNeedingCheckupController controller
    +ListVehiclesNeedingCheckupUI()
    +getController(): ListVehiclesNeedingCheckupController
}

Class ListVehiclesNeedingCheckupController {
    -CheckupRepository checkupRepository
    -VehicleRepository vehicleRepository
    +getVehiclesNeedingCheckup()
    +getCheckupRepository()
    +getVehicleRepository()
}

Class Repositories{
    -Repositories()
    +getInstance()
    +getVehicleRepository()
    +getCheckupRepository()
}

Class VehicleRepository {
    -List<Vehicle> vehicleList
    -getVehiclesNeedingCheckup()
    -getVehicles()
    -needsCheckup()
    -addVehicle(Vehicle vehicle)
}

Class CheckupRepository {
    -List<Checkup> checkupList
    -getCheckups(Vehicle vehicle)
}

Class VehicleNeedingCheckup{
    -Vehicle vehicle
    -int lastCheckupKm
    -int optimalNextCheckupKm
    +VehicleNeedingCheckup(Vehicle vehicle, int lastCheckupKm, int optimalNextCheckupKm)
}

ListVehiclesNeedingCheckupUI ..> ListVehiclesNeedingCheckupController
ListVehiclesNeedingCheckupController ..> Repositories : "repositories"
ListVehiclesNeedingCheckupController ..> VehicleRepository : vehicleRepository
VehicleRepository ..> CheckupRepository : checkupRepository
Repositories --> "1" VehicleRepository
Repositories --> "1" CheckupRepository
VehicleRepository ..> VehicleNeedingCheckup : vehicleNeedingCheckup
Repositories -> Repositories : "instance"


@enduml