@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US008 - Sequence Diagram

autonumber

actor "Fleet Manager" as Employee
participant ":ListVehiclesNeedingCheckupUI" as UI
participant ":ListVehiclesNeedingCheckupController" as CTRL
participant ":Repositories" as Repos
participant "repositories\n:Repositories" as PLAT
participant "checkupRepositoty\n:CheckupRepository" as CheckupRepo
participant "vehicleRepository\n:VehicleRepository" as VRepo
participant ":VehicleNeedingCheckup" as VehicleNeedCheckup

activate Employee
    Employee -> UI : Requests to show the list of \nvehicles needing a check-up
    activate UI

        UI -> CTRL** : create
        UI -> CTRL : getVehiclesNeedingCheckup()
        activate CTRL

            CTRL -> Repos : getInstance()
            activate Repos

                Repos --> CTRL : repositories
            deactivate Repos

            CTRL -> PLAT : getCheckupRepository()
            activate PLAT

                PLAT --> CTRL : checkupRepository
            deactivate PLAT

            CTRL -> CheckupRepo : getVehicleCheckupList()
            activate CheckupRepo

                CheckupRepo --> CTRL : checkupsList
            deactivate CheckupRepo

            CTRL -> Repos : getInstance()
            activate Repos

                Repos --> CTRL : repositories
            deactivate Repos

            CTRL -> PLAT : getVehicleRepository()
            activate PLAT

                PLAT --> CTRL : vehicleRepository
            deactivate PLAT

            CTRL-> VRepo : getVehiclesNeedingCheckup(checkupsList)
            activate VRepo

                VRepo --> VRepo : getVehicleList()

                loop for each vehicle in the vehicleList
                    VRepo --> VRepo : needsCheckup(vehicle, checkupsList)
                    activate VRepo

                        VRepo --> VRepo : getLastCheckupKms(vehicle, checkupsList)
                        VRepo --> VRepo : true
                    deactivate VRepo

                        VRepo --> VehicleNeedCheckup** : new VehicleNeedingCheckup(vehicle, lastCheckupKm, optimalNextCheckupKms)
                    VRepo --> VRepo : add(vehicleNeedingCheckup)
                end loop
                VRepo --> CTRL : vehiclesNeedingCheckup
            deactivate VRepo
            CTRL --> UI : vehiclesNeedingCheckup
        deactivate CTRL

        UI -> Employee : Shows the list of vehicles needing check-up by their\nPlateID, Brand, Model, currentKm, checkupFrequencyKm,\nlastCheckupKm and optimalNextCheckupKm

    deactivate UI

@enduml