@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0
title US020 - Class Diagram

package GUI <<Folder>> #DDDDDD {

class RegisterGreenSpaceUI {
    - string type
    - string name
    - string street
    - int streetNumber
    - string postalCode
    - string city
    - string district
    - double totalArea
    +RegisterGreenSpaceUI()
    +initialize()
    -fillGreenSpaceType()
    (...)
}
}

package Controller <<Folder>> #DDDDDD {
class RegisterGreenSpaceController {

    + RegisterGreenSpaceController()
    - getGreenSpaceRepository()
    + registerGreenSpace(greenSpaceDTO)
    }
}

package Repository <<Folder>> #DDDDDD {
class GreenSpaceRepository{
    - List<GreenSpace> greenSpaceList

    + GreenSpaceRepository()
    + registerGreenSpace(greenSpace)
    + add(greenSpace)
    - validateGreenSpace(newGreenSpace)
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getGreenSpaceRepository()
}

class ApplicationSession{
    - ApplicationSession()
    + getInstance() : ApplicationSession
    + getAuthenticationRepository()
    + getCurrentSession()

}

class UserSession{
    + getUserEmail()

}

class Email{

}

}


package Domain <<Folder>> #DDDDDD {
class GreenSpace {
    - GreenSpaceType type
    - String name
    - double totalArea
    - String manager
    + GreenSpace(type,name,street, streetNumber,\npostalCode,city,district,totalArea, manager)
    - validateType(type)
    - validateName(name)
    - validateTotalArea(totalArea)
}







class Address{
    - String street
    - int streetNumber
    - String postalCode
    - String city
    - String district
    + Address(street, streetNumber, postalCode, city, district)
    (...)
}
}


package Mapper <<Folder>> #DDDDDD {
class GreenSpaceMapper{
    + GreenSpaceMapper()
    + toGreenSpace(greenSpaceDTO, managerEmail)

}
}

package DTO <<Folder>> #DDDDDD {
class GreenSpaceDTO{
public String name
    + GreenSpaceType type
    + Double totalArea
    + String street
    + int streetNumber
    + String postalCode
    + String city
    + String district
    + GreenSpaceDTO(name, type, totalArea, street, streetNumber, postalCode, city, district)
    + addressToString()
}
}



RegisterGreenSpaceUI .down.> RegisterGreenSpaceController
RegisterGreenSpaceController ..> "1" GreenSpaceRepository : greenSpaceRepository
GreenSpaceRepository "1"-down-> "*" GreenSpace : greenSpace
GreenSpace *--"1" Address : address
RegisterGreenSpaceController ..> Repositories : repositories
Repositories --> "1" GreenSpaceRepository
Repositories -> Repositories : instance

RegisterGreenSpaceController ..> ApplicationSession

ApplicationSession -> ApplicationSession : instance
ApplicationSession --> "1" UserSession : userSession
UserSession ..> Email
RegisterGreenSpaceController ..> GreenSpaceMapper
GreenSpaceMapper ..> GreenSpaceDTO
RegisterGreenSpaceController ..> GreenSpaceDTO

@enduml