@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US020 - Sequence Diagram (SD)

autonumber

actor "Green Space\nManager" as GSM
participant ":RegisterGreenSpaceUI" as UI
participant ":GreenSpaceDTO" as DTO
participant ":RegisterGreenSpaceController" as CTRL
participant ":Repositories" as REPO
participant "repositories\n:Repositories" as REPOInstance
participant ":GreenSpaceMapper" as Mapper
participant ":ApplicationSession" as APP
participant "singleton\n:ApplicationSession" as APPSingleton
participant "userSession\n:UserSession" as UserSession
participant "userID\n:Email" as Email
participant ":greenSpaceRepository" as GSRepo

activate GSM

    GSM -> UI : asks to create a new Green Space
    activate UI



loop until typed data is validated
        UI --> GSM : requests data (name, type, area, street,\n streetNumber, postalCode, city, district)
    deactivate UI

    GSM -> UI : types requested data

    activate UI
    UI --> UI: Validates input data
    |||
end loop
        UI --> UI : keepData(name, type, area, street,\n streetNumber,postalCode, city, district)
        UI --> GSM : shows all data and requests confirmation
    deactivate UI

    GSM -> UI : confirms data
    activate UI

        UI -> DTO** : new GreenSpaceDTO(name, type, area, street,\n streetNumber,postalCode, city, district)

|||
        UI --> CTRL : registerGreenSpace(greenSpaceDTO)
        activate CTRL



            CTRL --> APP : getInstance()
            activate APP

                APP --> CTRL : singleton
            deactivate APP

            CTRL --> APPSingleton : getUserSession()
            activate APPSingleton

                APPSingleton --> CTRL : userSession
            deactivate APPSingleton

            CTRL --> UserSession : getUserId()
            activate UserSession

                UserSession --> CTRL : userId
            deactivate UserSession

            CTRL --> Email : getEmail()
            activate Email

                Email --> CTRL : email
            deactivate Email
            |||


            CTRL --> Mapper : toGreenSpace(greenSpaceDTO,managerEmail)
            |||
            activate Mapper
                ref over Mapper
                SD_toGreenSpaceDomainObject
                end ref

                Mapper --> CTRL : greenSpace

            deactivate Mapper

            |||
            CTRL --> REPO : getInstance()
                        activate REPO

                            REPO --> CTRL : repositories
                        deactivate REPO

                        CTRL --> REPOInstance : getGreenSpaceRepository()
                        activate REPOInstance

                            REPOInstance --> CTRL : greenSpaceRepository
                        deactivate REPOInstance

            CTRL --> GSRepo : registerGreenSpace(greenSpace)
            activate GSRepo

                GSRepo --> GSRepo : add(greenSpace)
                GSRepo --> GSRepo : validateGreenSpace(greenSpace)
                GSRepo --> CTRL : operation success
            deactivate GSRepo


            CTRL --> UI : operation success
        deactivate CTRL

        UI --> GSM : displays operation success
        deactivate UI
    deactivate GSM

@enduml