@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "GSM" as GSM
participant ":AgendaUI" as UI
participant ":PostPoneTaskPopupUI" as Popup

activate GSM

    GSM -> UI : Asks to postpone an entry on Agenda

    activate UI
        loop until doesn't select a valid option
        UI --> GSM : Shows the tasks of the Agenda and asks to\nselect the task to be postponed
    deactivate UI

    GSM -> UI : Selects a task
    activate UI
    UI --> UI : validates selected option
        |||
        end

        UI --> UI : keepData(task)
        |||

        UI -> Popup : show the popup to select a new execution date,\nstarting hours and starting minutes
    deactivate UI

    activate Popup
loop until typed data is valid
        Popup --> GSM : asks to type the required data (new execution date, start hour and start minute)
    deactivate Popup

    GSM -> Popup : Types requested data (executionDate, startHour, startMinute)
    activate Popup

        Popup -> Popup : validateExecutionDate()
        Popup -> Popup : validateTime()
end loop
        Popup --> UI : sends executionDate, startHour and startMinute\nback to main UI
    deactivate Popup

    activate UI
        |||
        UI --> UI : Postpone task by setting the status of the\nselected task to "Postponed", creating a copy\nof the selected task with the new workPeriod\n,removes the old workPeriod from the Team\n and from the vehicles assigned to the postponed\ntask.
        |||
        UI --> GSM : Display operation success


    deactivate UI

deactivate GSM


@enduml