@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model

class Organization {
    name
    nif
    website
    phoneNumber
    email
}

class Skill{
    name
    description
}

class Collaborator{
    name
    admissionDate
    birthDate
    phoneNumber
    email
    idDocType
    idDocNumber
}

class Job{
    name
}

class HRM{

}

class Team{
    name
    description
    members
    status
}

class Vehicle{
    plateId
    brand
    model
    type
    tare
    grossWeight
    currentKm
    registerDate
    acquisitionDate
    checkupFrequencyKms
}

class Checkup{
    date
    checkupKms
}

Organization "1" -- "*" Skill : "owns >"
HRM "1" -- "*" Skill : "register >"
Organization "1" -- "*" Job : "owns >"
HRM "1" -- "*" Job : "register >"
HRM "1" -- "*" Collaborator : "register >
Organization "1" -- "*" Collaborator : "has >"
HRM "1" -- "*" Collaborator : "assigns skills to >"
Collaborator "1" -- "*" Skill : "has >"
Collaborator "1" -- "1" Job : "has >"
Team "1" -- "*" Collaborator : "has >"
HRM "1" -- "*" Team : "generates >"
Organization "1" -- "*" Vehicle : "owns >"
FM "1" -- "*" Vehicle : "registers >"
FM "1" -- "*" Vehicle : "lists needing check-up >"
Vehicle "1" -- "*" Checkup : "does >"
FM "1" -- "*" Checkup : "registers >"

@enduml