@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title SD_obtainTeamDTO

autonumber

participant ":AgendaController" as AGENDA_CTRL

participant ":CollaboratorMapper" as CollaboratorMapper
participant ":CollaboratorDTO" as CollaboratorDTO
participant ":TeamMapper" as TeamMapper
participant ":TeamDTO" as TeamDTO

activate AGENDA_CTRL

    AGENDA_CTRL -> AGENDA_CTRL : getMembers() [Team]

    |||

    AGENDA_CTRL -> CollaboratorMapper : toDTOlist(teamMembers)
    activate CollaboratorMapper
    loop for each collaborator in teamMembers
    |||
                CollaboratorMapper -> CollaboratorDTO** : toDTO(collaborator)



                 CollaboratorMapper --> CollaboratorMapper : add(collaboratorDTO)

    end loop
                CollaboratorMapper --> AGENDA_CTRL : collaboratorDTOlist
                deactivate CollaboratorMapper
                |||

    AGENDA_CTRL -> TeamMapper : toDTO(collaboratorDTOlist)
    activate TeamMapper
    TeamMapper -> TeamDTO** : new TeamDTO(collaboratorDTOList)
    |||
    TeamMapper --> AGENDA_CTRL : teamDTO
    deactivate TeamMapper


deactivate AGENDA_CTRL

@enduml
