@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US023 - Sequence Diagram

autonumber


actor "Green Space\nManager" as GSM
participant ":AgendaUI" as UI
participant ":SelectTeamPopupUI" as POPUP
participant ":AgendaController" as AGENDA_CTRL
participant ":AssignTeamToEntryAgendaController" as CTRL
participant ":Repositories" as REPO
participant "repositories\n:Repositories" as REPOInstance
participant "agendaRepository\n:AgendaRepository" as AgendaRepository

activate GSM

GSM -> UI: asks to assign team to an entry in the agenda
activate UI

    UI -> AGENDA_CTRL : getAgendaTaskDTOManagerList()
    activate AGENDA_CTRL
    |||
    ref over AGENDA_CTRL
    SD_managerSpecificAgendaDTO

    end ref
    AGENDA_CTRL --> UI : managerSpecificAgendaDTO
    deactivate AGENDA_CTRL

    loop until doesn't select a valid option

    UI --> GSM: shows the list of tasks in the agenda and\nasks to select one
deactivate UI

GSM -> UI : selects a task
activate UI
UI --> UI : validates selected option
|||
end loop

    UI --> UI : keepData(task)

    |||
    UI -> POPUP : Shows the popup with the list of teams\n                 fillTeamTable()
    deactivate UI
    activate POPUP

    POPUP -> CTRL : getTeams()
    activate CTRL

    ref over CTRL
    SD_getTeamListDTO

    end ref

    CTRL --> POPUP : teamListDTO
    deactivate CTRL



    |||
    loop until doesn't select a valid option
    POPUP --> GSM: Shows the list of teams and asks to select one
deactivate POPUP

GSM -> POPUP : selects a team
activate POPUP
POPUP --> POPUP : validates selected option
end loop
|||
POPUP --> UI : Sends selected team to Main UI
deactivate POPUP
activate UI
    |||
    UI --> UI : keepData(selectedTeam)
    |||

    UI -> CTRL : assignTeamToTaskAgenda(selectedTask, selectedTeam)
    activate CTRL

    ref over CTRL
    SD_getTeamDomainObject

    end ref
    CTRL -> CTRL : teamObj

    CTRL -> REPO : getInstance()
                        activate REPO

                            REPO --> CTRL : repositories
                        deactivate REPO
                        CTRL -> REPOInstance: getAgendaRepository()

                        activate REPOInstance

                            REPOInstance --> CTRL : agendaRepository
                        deactivate REPOInstance

                    CTRL -> AgendaRepository : assignTeamToTaskAgenda(title, greenSpaceName, workStartDate, status, teamObj)
                    activate AgendaRepository

                    AgendaRepository -> Task** : assignTeam(team)
                    activate Task
                    alt team is available

                    Task -> Team** : addWorkPeriod(workPeriod)

                    else team is not available

                    note over Task, Team
                    An error message will be shown indicating
                          the selected team is not available
                    end note
                    deactivate Task

                    end

                    AgendaRepository --> CTRL : task Optional
                deactivate AgendaRepository
            loop for every collaborator in the selectedTeam
            |||
                    ref over CTRL
                        SD_sendEmailToCollaborator

                        end ref
                        |||
            end loop
                    deactivate AgendaRepository



    CTRL --> UI : operation success

    deactivate CTRL



    UI --> GSM: shows operation success
deactivate UI

@enduml