@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho


skinparam classAttributeIconSize 0
hide circle
hide methods

title US005 - Domain Model

class Organization {
    name
    nif
    website
    phoneNumber
    email
}

class Team{
    name
    description
    members
    status
}

class Collaborator{
    name
    admissionDate
    birthDate
    phoneNumber
    email
    idDocType
    idNumber
}

Organization "1" -- "*" Collaborator : "has >"
Team "1" --left "*" Collaborator : "has >"
HRM "1" -- "*" Team : "generates >"
@enduml