@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto
skinparam classAttributeIconSize 0
'left to right direction

Repositories -> Repositories : instance


Repositories --> "1" VehicleRepository
Repositories --> "1" VehicleCheckupRepository

VehicleRepository --> "*" VehicleCheckup

VehicleCheckup ..> Date : checkupDate
RegisterCheckupController ..> Repositories : repositories
RegisterCheckupUI ..> RegisterCheckupController
RegisterCheckupController ..> VehicleRepository : vehicleRepository
RegisterCheckupController ..> VehicleCheckupRepository : vehicleCheckupRepository

class RegisterCheckupUI {

}

class RegisterCheckupController {
    + getVehicleList()
    + registerVehicleCheckup(vehicle, checkupDate, checkupKm)
}

class Repositories {
    + getInstance()
    + getVehicleRepository()
    + getVehicleCheckupRepository()
}

class VehicleRepository {
    + getVehicles()
}

class VehicleCheckupRepository {
    + registerVehicleCheckup(vehicle, checkupDate, checkupKm)
    + addCheckup(vehicleCheckup)
    + validateCheckup(vehicleCheckup)
}

class VehicleCheckup {
    + VehicleCheckup(vehicle, checkupDate, checkupKm)
    + validateCheckupKm()
}

class Date {
    + validateDate(checkupDate)
}

@enduml
