@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US007 - System Sequence Diagram (SSD)

autonumber

actor "Fleet Manager" as Employee
participant ":RegisterCheckupUI" as UI
participant ":RegisterCheckupController" as RCCtrl
'participant "taskCategoryRepository:\nTaskCategoryRepository" as TaskCategoryRepository
'participant ":ApplicationSession" as _APP
'participant "appSession\n:ApplicationSession" as APP
'participant "currentSession\n:UserSession" as SESSAO
'participant "vehicleRepository:\nVehicleRepository" as VehicleRepository
participant ":Organization" as Organization
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant ":vehicleCheckupRepository\n:VehicleCheckupRepository" as VCRepo
'participant "organizationRepository:\nOrganizationRepository" as OrganizationRepository
participant ":Vehicle Checkup" as VCheckup

activate Employee

    Employee -> UI : Asks to register a new vehicle's check-up
    activate UI

        UI --> RCCtrl** : create
        UI --> RCCtrl : getVehicles()
        activate RCCtrl

            RCCtrl --> Organization : getAllVehicles()
            activate Organization

                Organization --> RCCtrl : vehiclesList
            deactivate Organization

            RCCtrl --> UI : vehiclesList
        deactivate RCCtrl

        UI --> Employee : Shows the list of vehicles and asks to select one
    deactivate UI

    Employee -> UI : Selects a vehicle
    activate UI

        UI --> UI : keepVehicle(Vehicle)
        UI --> Employee : registerVehicleCheckup(vehicle, \ndateOfCheckup, \ncurrentKms)
    deactivate UI

    Employee --> UI : Types requested data
    activate UI

        UI --> UI : keepData(Date of check-up, \nCurrent kilometers)
        UI --> Employee : Shows all data and requests confirmation
    deactivate UI

    Employee -> UI : Confirms data
    activate UI

        UI --> RCCtrl : registerVehicleCheckup(Vehicle, \nDate of check-up, \nCurrent kilometers)
        activate RCCtrl

            RCCtrl --> RepositorySingleton : getInstance()
            activate RepositorySingleton

                RepositorySingleton --> RCCtrl : repositories
            deactivate RepositorySingleton
            RCCtrl --> PLAT : getVehicleCheckupRepository()
            activate PLAT

                PLAT --> RCCtrl : VehicleCheckupRepository
            deactivate PLAT
            RCCtrl --> VCRepo : registerVehicleCheckup(vehicle, \ndateOfCheckup, \ncurrentKms)
            activate VCRepo

                VCRepo --> VCheckup** : create(Vehicle, Date of check-up, Current kilometers)
                note right of VCheckup
                    VehicleCheckup constructor
                    normally validates arguments
                end note
                VCRepo --> VCRepo : validateCheckup(vehicleCheckup)
                VCRepo --> VCRepo : addCheckup(vehicleCheckup)
                VCRepo --> RCCtrl : vehicleCheckup
            deactivate VCRepo

            RCCtrl --> UI : vehicleCheckup
        deactivate RCCtrl

        UI --> Employee : Displays operation success
    deactivate UI

@enduml