@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US003 - System Sequence Diagram (SSD)

autonumber

actor "HRM" as Employee
participant ":RegisterCollabUI" as System

activate Employee

    Employee -> System : Asks to register a collaborator

    activate System
        |||
        System --> Employee : Requests data (name, birthdate, admission date, address, \nemail,mobile number, id doc type, id doc number)
    deactivate System

    loop until typed data is validated
    Employee -> System : Types requested data

    activate System

        System --> Employee : Shows job list and asks to select one
    deactivate System

    Employee -> System : Selects a job

    activate System
        |||
        System --> System : validatesData
        |||
        System --> Employee : Shows all data and requests confirmation
    deactivate System
    end
    Employee -> System : Confirms data

    activate System
        System --> System : keepsData(name, birthdate, admission\ndate, address, email,mobile number,\nid doc type, id doc number, jobName)
        |||
        System --> Employee : Displays operation success
    deactivate System

@enduml