@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US003 - System Sequence Diagram (SSD)

autonumber

actor "HRM" as HRM
participant ":RegisterCollaboratorUI" as UI

activate HRM

    HRM -> UI : Asks to register a collaborator

    activate UI
    loop until typed data is validated

        UI --> HRM : Requests data (name, birthdate, admissionDate,\n street, streetNumber, postalCode, city, district,\n email, mobileNumber, idDocType, idDocNumber)
    deactivate UI

    HRM -> UI : Types requested data

    activate UI
    |||

    end
    |||
        UI --> UI : keepData(name, birthdate, admissionDate,\n street, streetNumber, postalCode, city, district,\n email, mobileNumber, idDocType, idDocNumber)
        |||


         loop until doesn't select a valid option
                UI --> HRM : Shows job list and asks to select one
            deactivate UI

            HRM -> UI : Selects a job

            activate UI
            |||
            end

        UI --> UI : keepData(Job job)
        UI --> HRM : Shows all data and requests confirmation
    deactivate UI

    HRM -> UI : Confirms data

    activate UI

        UI --> HRM : Displays operation success
    deactivate UI

@enduml