    @startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US002 - System Sequence Diagram (SSD)

autonumber

actor "HRM" as HRM
participant ":RegisterJobUI" as UI

activate HRM

    HRM -> UI : Asks to register a new job
    activate UI
    loop until typed data is validated
        UI --> HRM : Requests data (job name)
    deactivate UI

    HRM -> UI : Types requested data
    activate UI
    |||
    end
    UI --> UI : keepData(jobName)
    |||

        UI --> HRM : Shows typed data and requests confirmation
    deactivate UI


    HRM -> UI : Confirms data and submits
    activate UI



        UI --> HRM : Displays operation success
    deactivate UI

@enduml