@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US022 - Sequence Diagram

autonumber

actor "GSM" as GSM
participant ":AddNewEntryAgendaUI" as UI
participant ":InsertDatePopupUI" as Popup
participant ":AddNewEntryAgendaController" as CTRL
participant ":Repositories" as REPO
participant "repositories\n:Repositories" as REPOInstance
participant "agendaRepository\n:AgendaRepository" as AgendaRepository
participant "toDoRepository\n:ToDoRepository" as ToDoRepository

activate GSM

    GSM -> UI : Asks to add a new entry on Agenda

    activate UI


    UI -> CTRL : getToDoDTOManagerList()

    activate CTRL

    ref over CTRL
    SD_getToDoManagerList

    end ref

    CTRL --> UI : toDoDTOManagerList
    deactivate CTRL

        loop until doesn't select a valid option
        UI --> GSM : Shows the To-Do list and asks to select the task


    deactivate UI


    GSM -> UI : Selects a task
    activate UI
    UI --> UI : validates selected option
        |||
        end

        UI --> UI : keepData(selectedTask)
        |||

        UI -> Popup : Show the popup to insert task execution\ndate and hour
        deactivate UI
        |||
        activate Popup

        loop until typed data is validated

        Popup --> GSM : Asks to type requested data (execution date and hour for the selected task)
        deactivate Popup

    deactivate UI
    |||
    GSM -> Popup: Enters date (selectedDate) and time (workStartingHours, workStartingMins)
    activate Popup

    Popup --> Popup : validates typed data
    |||
    end loop
    |||

        Popup --> UI: Sends date and time data to Main UI
    deactivate Popup

    activate UI
        |||
        UI --> CTRL : registerTaskAgenda(selectedTask, selectedDate, workStartingHours, workStartingMins)
        |||

        activate CTRL

        ref over CTRL
        SD_toTaskDomainObject

        end ref

        CTRL -> CTRL : task
        |||

        CTRL -> REPO : getInstance()
                    activate REPO

                        REPO --> CTRL : repositories
                    deactivate REPO
                    CTRL -> REPOInstance: getAgendaRepository()

                    activate REPOInstance

                        REPOInstance --> CTRL : agendaRepository
                    deactivate REPOInstance

                CTRL -> AgendaRepository : registerTaskAgenda(task, executionDate, workStartingDays, workStartingMinutes)
                activate AgendaRepository

                AgendaRepository --> AgendaRepository : add(task, executionDate, workStartingDays,\nworkStartingMinutes)

                AgendaRepository --> AgendaRepository : validateTaskAgenda(task)

                |||
                AgendaRepository -> Task** : setStatus(AGENDA_DEFAULT_STATUS)

                note right
                                When a task enters the Agenda, the
                                default status of the task is
                                "PLANNED" and the task in To-Do
                                list will be "PROCESSED"
                                             end note

                AgendaRepository -> Task** : setTaskWorkPeriod(executionDate, workStartingHours,\nworkStartingMinutes, expectedDuration);



                AgendaRepository --> CTRL : taskOptional
                deactivate AgendaRepository



                CTRL -> REPO : getInstance()
                                    activate REPO

                                        REPO --> CTRL : repositories
                                    deactivate REPO
                                    CTRL -> REPOInstance: getToDoRepository()

                                    activate REPOInstance

                                        REPOInstance --> CTRL : toDoRepository
                                    deactivate REPOInstance

                                CTRL -> ToDoRepository : updateTaskToProcessed(task)
                                activate ToDoRepository

                                ToDoRepository -> Task** : setStatus(Status.PROCESSED)

                                ToDoRepository --> CTRL : operation success
                                deactivate ToDoRepository

                                CTRL --> UI : operation success

                deactivate CTRL


        UI --> GSM : Display operation success
    deactivate UI

deactivate GSM

@enduml
