@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US022 - Sequence Diagram

autonumber

actor "GSM" as GSM
participant ":AddNewEntryAgendaUI" as UI
participant ":AddNewEntryAgendaController" as CTRL
participant ":ToDo" as ToDo
participant ":Agenda" as Agenda
participant ":Task" as Task

activate GSM

    GSM -> UI : Asks to add a new entry on Agenda
    activate UI

        UI -> CTRL : getToDoList()
    activate CTRL

        CTRL -> ToDo : getToDoList()
        activate ToDo

            ToDo --> CTRL : toDoList
        deactivate ToDo

        CTRL --> UI : toDoList
    deactivate CTRL

        loop until doesn't select a valid option
        UI --> GSM : Shows the To-Do list and asks to select the task
    deactivate UI

    GSM -> UI : Selects a task
    activate UI
        |||
        end

        UI --> UI : keepData(task)
        |||

        UI --> GSM : Shows all data and requests confirmation
    deactivate UI

    GSM -> UI: Confirms data

    activate UI
        |||
        UI -> CTRL : addEntryToAgenda(task)

        activate CTRL

            CTRL -> Agenda : addEntryToAgenda(task)

            activate Agenda

                Agenda -> Task** : setStatusToPlanned()

                note right of Task
                    The task was pending on ToDo list by default

                    After adding the task to Agenda, the dafault
                    status is set to planned.

                end note

                Agenda --> Agenda : addTask(task)
                Agenda --> CTRL : operation success



            deactivate Agenda



            CTRL --> UI : operation success
        deactivate CTRL

        |||
        UI --> GSM : Display operation success


    deactivate UI






deactivate GSM


@enduml