@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US023 - System Sequence Diagram (SSD)

autonumber


actor "Green Space\nManager" as GSM
participant ":AgendaUI" as UI
participant ":SelectTeamPopupUI" as POPUP

activate GSM

GSM -> UI: asks to assign team to an entry in the agenda
activate UI

    loop until doesn't select a valid option

    UI --> GSM: shows the list of tasks in the agenda and\nasks to select one
deactivate UI

GSM -> UI : selects a task
activate UI
UI --> UI : validates selected option
|||
end loop

    UI --> UI : keepData(task)

    UI -> POPUP : Shows the popup with the list of teams
    deactivate UI
    activate POPUP
    |||
    loop until doesn't select a valid option
    POPUP --> GSM: Shows the list of teams and asks to select one
deactivate POPUP

GSM -> POPUP : selects a team
activate POPUP
POPUP --> POPUP : validates selected option
end loop
|||
POPUP --> UI : Sends selected team to Main UI
deactivate POPUP
activate UI
    |||
    UI --> UI : keepData(selectedTeam)
    |||
    UI -> UI : assigns the team to the selected task
    |||


    UI --> GSM: shows operation success
deactivate UI

@enduml