@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

title US020 - Domain Model


class GreenSpace {
  name
  size
}

class Garden {

}

class MediumPark {

}

class LargePark {

}

class Address{
    street
    streetNumber
    postalCode
    city
    district
}

GSM "1" -d- "*" GreenSpace : registers >
GreenSpace "1" --r "1" Address : is located at  >
Garden --r|> GreenSpace : "is a type of"
MediumPark --u|> GreenSpace : "is a type of"
LargePark --u|> GreenSpace : "is a type of"

@enduml