@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US021 - Sequence Diagram

autonumber

actor "GSM" as GSM
participant ":AddNewEntryToDoUI" as UI
participant ":AddNewEntryToDoController" as CTRL
participant ":Repositories" as REPO
participant "repositories\n:Repositories" as REPOInstance
participant "greenSpaceRepository\n:GreenSpaceRepository" as GreenSpaceREPO
participant "toDo\n:ToDo" as Todo
participant ":Task" as Task

activate GSM

    GSM -> UI : Asks to add a new entry on To-Do List
    activate UI

    UI -> CTRL : getGreenSpaceList()
    activate CTRL

        CTRL -> REPO : getInstance()
        activate REPO

            REPO --> CTRL : repositories
        deactivate REPO
        CTRL -> REPOInstance: getGreenSpaceRepository()

        activate REPOInstance

            REPOInstance --> CTRL : greenSpaceRepository
        deactivate REPOInstance

        CTRL -> GreenSpaceREPO : getGreenSpaceList()
        activate GreenSpaceREPO
        GreenSpaceREPO --> CTRL : greenSpaceList
        deactivate GreenSpaceREPO








CTRL --> UI : greenSpaceList
    deactivate CTRL


    loop until doesn't select a valid option
                    UI --> GSM : Shows list of green spaces and asks to select one
                deactivate UI

                GSM -> UI : Selects a green space

                activate UI
                |||
                end

            UI --> UI : keepData(greenspace)


    loop until typed data is validated

        UI --> GSM : Requests data (description, duration, urgency)
    deactivate UI

    GSM -> UI : Types requested data

    activate UI
    |||

    end

        UI --> UI : keepData(description, duration, urgency)
        |||


                UI --> GSM : Shows all data and requests confirmation
deactivate UI
    GSM -> UI : Confirms data

    activate UI

    UI -> CTRL : createNewTask(description, duration, urgency, greenSpace)
    activate CTRL

        CTRL -> Todo : createNewTask(description, duration, urgency, greenSpace)

        activate Todo

            Todo -> Task** : new Task (description, duration, urgency, greenSpace)

            Task --> Task : validateDescription(description)

            Task --> Task : validateDuration(duration)

            Task --> Task : validateUrgency(urgency)

           |||

            Todo --> Todo : validateTask(task)

            Todo --> Todo : addTask(task)

            Todo --> CTRL : operation success
            deactivate GreenSpaceREPO
            CTRL --> UI : operation success
            deactivate CTRL
        UI --> GSM : Displays operation success
    deactivate UI

@enduml