@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US021 - Sequence Diagram

autonumber

actor "GSM" as GSM
participant ":AddNewEntryToDoUI" as UI
participant "controller\n:AddNewEntryToDoController" as CTRL
participant ":ToDoTaskDTO" as ToDoTaskDTO
participant ":Repositories" as REPO
participant "repositories\n:Repositories" as REPOInstance
participant "toDoRepository\n:ToDoRepository" as Todo
participant "task\n:Task" as TaskSet



activate GSM

    GSM -> UI : Asks to add a new entry on To-Do List
    activate UI

    UI -> CTRL : getGreenSpaceDTOlist()
    activate CTRL
|||
        ref over CTRL
        SD_toGreenSpaceDTOlist
        end ref

CTRL --> UI : greenSpaceDTOList
    deactivate CTRL


    loop until doesn't select a valid option
                    UI --> GSM : Shows list of green spaces and asks to select one
                deactivate UI

                GSM -> UI : Selects a green space

                activate UI
                 UI --> UI: validates Selection
                |||
                end

            UI --> UI : keepData(greenspace)


    loop until typed data is validated

        UI --> GSM : Requests data (title, description, expected duration)
    deactivate UI

    GSM -> UI : Types requested data

    activate UI

    UI --> UI : validates typed data
    |||

    end

        UI --> UI : keepData(title, description, expectedDuration)
        note right of UI
                    expectedDuration is composed
                    by days, hours and minutes
                    end note
        |||

    loop until doesn't select a valid option
                        UI --> GSM : Shows list of task taskType and urgency and asks to select one
                    deactivate UI

                    GSM -> UI : Selects type of task and urgency
                    note right
                    Task type and urgency are
                    both enumerate types
                    end note
                    activate UI
                     UI --> UI: validates Selection
                    |||
                    end

                UI --> UI : keepData(type, urgency)


        |||





                UI --> GSM : Shows all data and requests confirmation
deactivate UI
    GSM -> UI : Confirms data

    activate UI

    UI -> ToDoTaskDTO** : new toDoTaskDTO(title, description, taskType, greenSpace,\nurgency, days, hours, minutes)
    |||
    UI -> CTRL : registerTask(toDoTaskDTO)
    activate CTRL

            ref over CTRL
            |||
            SD_toToDoDomainObject

            end ref
            CTRL -> CTRL : task
            note right
            The DTO is converted
            to domain object Task
            end note
            |||
            CTRL -> REPO : getInstance()
                    activate REPO

                        REPO --> CTRL : repositories
                    deactivate REPO
                    CTRL -> REPOInstance: getToDoRepository()

                    activate REPOInstance

                        REPOInstance --> CTRL : toDoRepository
                    deactivate REPOInstance

                    CTRL -> Todo : registerTaskTodo(task)

                    activate Todo

                    Todo --> Todo : validateTaskToDo(task)
                    |||
                    Todo -> TaskSet** : setStatus(TODO_DEFAULT_STATUS)
                    note right of TaskSet
                    When a new task is created, the
                    status is "PENDING" by default, until
                    the task doesn't go to the Agenda.
                    end note
                    Todo --> Todo : add(task)

                    Todo --> CTRL : operation success
                    deactivate Todo

            CTRL --> UI : operation success
            deactivate CTRL
        UI --> GSM : Displays operation success
    deactivate UI

@enduml