@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title US008 - Domain Model

class Organization {
    name
    nif
    website
    phoneNumber
    email
}

class Vehicle{
    plateId
    brand
    model
    type
    tare
    grossWeight
    currentKm
    registerDate
    acquisitionDate
    checkupFrequencyKms
}

class CheckupList{

}




FM "1" -- "*" CheckupList : " requests to show >"
Organization "1" --- "*" Vehicle : "owns >"
CheckupList "1" -- "1..*" Vehicle : "has >"




@enduml