@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title US002 Domain Model

class Job {
    name
}

'Platform "1" -- "*" Organization : has registered >
'Platform "1" -- "*" Category : defines >
@enduml