@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

'title Domain Model

class Organization {
    name
    vatNumber
    website
    phoneNumber
    email
}

class Employee {
    name
    admissionDate
    birthDate
    address
    contactInfo
    IdDocType
    IdNumber
}

class HRM{

}

class Collaborator{
    skills
    job
}

class Job{
    job name
}

Organization "1" --right "1..*" Employee
HRM "1" --left "1" Employee : "is >"
HRM "1" --down "0..*" Collaborator : "registers >"
Collaborator "1" -left "1" Job : "has >"

@enduml