@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0


class Date {
    - int day
    - int month
    - int year
    + enum Mes

-- Methods: --
    + Date(dateString)
    + Date()
    .. Getters:..
    + getDay()
    + getMonth()
    + getYear()
    .. Setters:..
    + setDate(date)
    + setDay(day)
    + setMonth(month)
    + setYear(year)
    ..Utils..
    - validateDate(date)
    - isLeapYear(year)
    + toString()
    + isPastDate()
    + getDateDifferenceInDays(date)
    - getDaysInMonth(month, year)
    + compareTo(dateCompare)
    + clone()
}

@enduml