@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class Team{
    name
    description
    members
    status
}

class Agenda{
    tasks
}

class Task{
    title
    description
    state
    urgency
    assignedGreenSpace
    assignedVehicle
    assignedTeam
    expectedDuration
}


Task "*" -u- "1" Agenda : "are part of >"
Team "1" -u- "0..*" Task : "is assigned to >"
GSM -- Task : "assigns a team to >"

@enduml