@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title US025 - Domain Model

'class Platform {
'  -description
'}



class Agenda{
    tasks
}

class Task{
    title
    description
    state
    urgency
    assignedGreenSpace
    assignedVehicle
    assignedTeam
    expectedDuration
}


Task "*" -u- "1" Agenda : "are part of >"
GSM -- Task : "cancel >"

@enduml