@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction
title US025 - Domain Model
skinparam classAttributeIconSize 0

hide circle
hide methods


class GSM {

}

class Agenda {

}



GSM "1" -- "1" Agenda : cancels an entry

@enduml