@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction
title US022 - Domain Model
skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class GSM {

}

class Agenda {

}

class ToDo

GSM "1" -- "1" Agenda : adds new entry
Agenda "1" -- "*" ToDo : previously included in
@enduml