@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US004 - Sequence Diagram

autonumber

actor "HRM" as HRM
participant ":AssignSkillUI" as UI
participant ":AssignSkillController" as CTRL
participant "organization\n:Organization" as ORG


activate HRM

    HRM -> UI : Asks to assign one or more skills to a collaborator

    activate UI

        UI -> CTRL : getListOfCollaborators()

        activate CTRL

            CTRL -> ORG : getListOfCollaborators()
            |||
            activate ORG

                ORG -> CTRL : ListOfCollaborators
            deactivate ORG
            CTRL -> UI : ListOfCollaborators
        deactivate CTRL
        UI --> HRM : Shows a list of Collaborators and asks to select one
    deactivate UI

    HRM -> UI : Selects a collaborator

    activate UI

        UI -> CTRL : getSkillList()

        activate CTRL

            CTRL -> ORG : getSkillList()
            |||
            |||

            activate ORG

                ORG -> CTRL : skillList

            deactivate ORG

            UI --> UI : keepCollaborator(collaborator)
            |||
            |||

            CTRL -> UI : skillList
        deactivate CTRL

        loop while doesn't choose to advance

            UI --> HRM : Displays a list of available skills and asks to \nselect one.
    deactivate UI

        HRM -> UI : Selects a skill

    activate UI

        end
        |||
        UI --> UI : keepSelectedSkills(List<Skills> skills)

        UI --> HRM : Shows all data (collaborator and his skills) and \nrequests confirmation
    deactivate UI

    HRM -> UI : Confirms the operation
    activate UI

        UI -> CTRL : addSkillsToCollaborator(collaborator, List<Skills> skills)

        activate CTRL

            CTRL -> ORG : addSkillsToCollaborator(collaborator, List<Skills> skills)
            |||
            activate ORG

                ORG ->CTRL : show Collaborator
            deactivate ORG
            CTRL -> UI : show Collaborator
        deactivate CTRL

        UI --> HRM : Displays operation success
    deactivate UI

@enduml