@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title SD_toGreenSpaceDTOList

autonumber

participant ":ListGreenSpacesController" as CTRL
participant ":GreenSpaceMapper" as GSMapper
participant ":GreenSpaceDTO" as GSDto


        activate CTRL
            CTRL -> GSMapper : toDTOList(managerGreenSpacesList)
            activate GSMapper

                    loop for every greenSpace in managerGreenSpacesList
                    GSMapper -> GSDto : toDTO(greenSpace)
                    activate GSDto

                        GSDto --> GSMapper : greenSpaceDTO
                    deactivate GSDto
                    |||
                    GSMapper --> GSMapper : add(greenSpaceDTO)
                end loop

                GSMapper --> CTRL : greenSpaceDTOList
            deactivate GSMapper






@enduml