@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US027 - Sequence Diagram

autonumber

actor "Green Space\nManager" as GSM
participant ":ListGreenSpacesUI" as UI
participant ":ListGreenSpacesController" as CTRL

participant ":GreenSpaceMapper" as GSMapper

participant ":ApplicationSession" as APP
participant "singleton\n:ApplicationSession" as APPSingleton
participant "userSession\n:UserSession" as UserSession
participant "userID\n:Email" as Email


participant ":Repositories" as REPO
participant "repositories\n:Repositories" as REPOInstance
participant "greenSpaceRepository\n:GreenSpaceRepository" as GSRepo

participant ":GreenSpaceSorting" as GreenSpaceSorting
participant ":ApplicationSession" as ApplicationSession



activate GSM

    GSM -> UI : asks to list all the green spaces managed by me
    activate UI


        UI -> CTRL : getGreenSpaces()
        activate CTRL

        CTRL -> APP : getInstance()
            activate APP

                APP --> CTRL : singleton
            deactivate APP

            CTRL -> APPSingleton : getUserSession()
            activate APPSingleton

                APPSingleton --> CTRL : userSession
            deactivate APPSingleton

            CTRL -> UserSession : getUserId()
            activate UserSession

                UserSession --> CTRL : userId
            deactivate UserSession

            CTRL -> Email : getEmail()
            activate Email

                Email --> CTRL : email
            deactivate Email

            CTRL -> CTRL : managerEmail
            |||






            CTRL -> REPO : getInstance()
            activate REPO

                REPO --> CTRL : repositories
            deactivate REPO

            CTRL -> REPOInstance : getGreenSpaceRepository()
            activate REPOInstance

                REPOInstance --> CTRL : greenSpaceRepository
            deactivate REPOInstance

            CTRL -> GSRepo : getGreenSpaceListByManager(managerEmail)
            activate GSRepo

                GSRepo --> CTRL : managerGreenSpacesList
            deactivate GSRepo

            |||

            CTRL -> GreenSpaceSorting : sort(managerGreenSpacesList)
            activate GreenSpaceSorting

            GreenSpaceSorting -> ApplicationSession : getInstance().getProperties()
            activate ApplicationSession

            ApplicationSession -> ApplicationSession : getProperty(ApplicationSession.SORTING_ALGORITHM)


            ApplicationSession --> GreenSpaceSorting : Sorting.Algorithm
            deactivate ApplicationSession
            |||
            alt Sorting.Algorithm on properties is bubbleSort

            GreenSpaceSorting -> GreenSpaceSorting : bubbleSort(managerGreenSpacesList))
            |||
            else Sorting.Algorithm on properties is selectionSort

            GreenSpaceSorting -> GreenSpaceSorting : selectionSort(managerGreenSpacesList))
            |||
            end


            GreenSpaceSorting --> CTRL : sorted managerGreenSpacesList

            deactivate GreenSpaceSorting
            |||
            note over CTRL
            at this point the managerGreenSpacesList
                                  is now sorted
            end note


            |||




            CTRL -> GSMapper : toDTOList(managerGreenSpacesList)
            |||
            activate GSMapper
            ref over GSMapper
                        SD_toGreenSpaceDTOList

                        end ref



                GSMapper --> CTRL : greenSpaceDTOList
            deactivate GSMapper

            CTRL --> UI: greenSpaceDTOList
            deactivate CTRL

            UI --> GSM : displays all the green spaces managed by the GSM

             deactivate UI

@enduml