@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US027 - Sequence Diagram (SD)

autonumber

actor "Green Space\nManager" as GSM
participant ":ListGreenSpacesUI" as UI
participant ":ListGreenSpacesController" as CTRL
participant ":Repositories" as REPO
participant "repositories\n:Repositories" as REPOInstance
participant "greenSpaceRepository\n:GreenSpaceRepository" as GSRepo
participant ":GreenSpaceMapper" as GSMapper
participant ":GreenSpaceDTO" as GSDto
participant ":ConfigLoader" as Config
participant ":Sorter" as Sorter


activate GSM

    GSM -> UI : asks to list all the green spaces managed by me
    activate UI

        UI -> CTRL** : create
        UI -> CTRL : getGreenSpaces()
        activate CTRL

            CTRL -> REPO : getInstance()
            activate REPO

                REPO --> CTRL : repositories
            deactivate REPO

            CTRL -> REPOInstance : getGreenSpaceRepository()
            activate REPOInstance

                REPOInstance --> CTRL : greenSpaceRepository
            deactivate REPOInstance

            CTRL -> GSRepo : getGreenSpaceList()
            activate GSRepo

                GSRepo --> CTRL : greenSpaceList
            deactivate GSRepo

            CTRL -> GSMapper : getDTOList(greenSpaceList)
            activate GSMapper

                loop for every greenSpace in greenSpaceList
                    GSMapper -> GSDto : toDTO(greenSpace)
                    activate GSDto
                        note right of GSDto
                            greenSpaceDTO contains the name of the green space,
                            it's size, the city where it is located and the
                            type of green space it is.
                        end note
                        GSDto --> GSMapper : greenSpaceDTO
                    deactivate GSDto
                    GSMapper --> GSMapper : add(greenSpaceDTO)
                end loop

                GSMapper --> CTRL : greenSpaceDTOList
            deactivate GSMapper

            CTRL -> ConfigLoader : getSortingAlgorithm()
            activate ConfigLoader

                ConfigLoader --> CTRL : sortingAlgorithm
            deactivate ConfigLoader

            CTRL -> Sorter : sort(greenSpaceDTOList, sortingAlgorithm, columnToSort)
            activate Sorter

                Sorter --> CTRL : sortedGreenSpaceDTOList
            deactivate Sorter

            CTRL --> UI : sortedGreenSpaceDTOList
        deactivate CTRL

        UI --> GSM : displays all the green spaces\nmanaged by the GSM
    deactivate UI

@enduml