@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US025 - System Sequence Diagram (SSD)

autonumber

actor "GSM" as GSM
participant ":AgendaUI" as UI


activate GSM

    GSM -> UI : Asks to cancel an entry on Agenda

    activate UI
        loop until doesn't select a valid option
        UI --> GSM : Shows the tasks of the Agenda and asks to\nselect the task to be canceled
    deactivate UI

    GSM -> UI : Selects a task
    activate UI
    UI --> UI : validates selected option
        |||
        end

        UI --> UI : keepData(task)
        |||

        UI --> GSM : Shows cancel task message and asks for confirmation
    deactivate UI

    GSM -> UI: Confirms the operation

    activate UI
        |||
        UI --> UI : Cancel task by setting the status of the\nselected task to "Canceled" and removes\n frees the Team and vehicle from the task\nworking period
        |||
        UI --> GSM : Display operation success


    deactivate UI






deactivate GSM


@enduml