@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0


class Collaborator {
     - String name
     - Date admissionDate
     - Date birthDate
     - String phoneNumber
     - String idDocType
     - int idDocNumber
}

class Job {
    - String jobName
}

class Date {
    - int day
    - int month
    - int year
}

class Organization {
    - String name
    - int nif
    - String website
    - String phone
    - String email
}

class JobReposity {
    + add(job)
    + validateJob(job)
    + getJob()
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getJobRepository()
}

note bottom of JobReposity
    - used for displaying
    the job list
end note

class RegisterCollaboratorController {
    + CreateTaskController(organizationRepository, taskCategoryRepository)
    + getJobList()
    + createCollaborator(name, birthdate, admission date, address, email,\nmobile number, id doc type, id doc number, jobName)
}

class RegisterCollaboratorUI {
}

class Email{
    - String email
}

class Address{
    - String street
    - int streetNumber
    - String postalCode
    - String city
    - String district

}

RegisterCollaboratorUI .right.> RegisterCollaboratorController
RegisterCollaboratorController ..> Organization
Organization -down-> Collaborator
RegisterCollaboratorController ..> JobReposity
JobReposity --> Job
Collaborator --> Job
Collaborator --> Email
Collaborator --> Address
Collaborator --> Date
RegisterCollaboratorController ..> Repositories
Repositories --> JobReposity


@enduml