@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0


class Collaborator {
     - String name
     - Date admissionDate
     - Date birthDate
     - String phoneNumber
     - String idDocType
     - int idDocNumber
}

class Job {
    - String jobName
}

class Date {
    - int day
    - int month
    - int year
}

class CollaboratorRepository{
}

class JobRepository {
    + add(job)
    + validateJob(job)
    + getJob()
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getJobRepository()
}

note right of JobRepository
    - used for displaying
    the job list
end note

class RegisterCollaboratorController {
    + RegisterCollaboratorController("Fill in this field later")
    + getJobList()
    + createCollaborator(name, birthdate, admission date, address, email,\nmobile number, id doc type, id doc number, jobName)
}

class RegisterCollaboratorUI {
}

class Email{
    - String email
}

class Address{
    - String street
    - int streetNumber
    - String postalCode
    - String city
    - String district

}

RegisterCollaboratorUI .right.> RegisterCollaboratorController
RegisterCollaboratorController ..> "1" CollaboratorRepository : organization
CollaboratorRepository -down-> Collaborator
RegisterCollaboratorController ..> JobRepository
JobRepository "1"-->"*" Job : job
Collaborator --> Job
Collaborator --> Email
Collaborator --> Address
Collaborator ..> Date
RegisterCollaboratorController ..> Repositories
Repositories --> "1" JobRepository
Repositories --> "1" CollaboratorRepository
Repositories -> Repositories : instance


@enduml