@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US003 - Sequence Diagram

autonumber

actor "HRM" as HRM
participant ":RegisterCollaboratorUI" as UI
participant ":RegisterCollaboratorController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "jobRepository:\nJobRepository" as JobRepository
participant ":collaboratorRepository \nCollaboratorRepository" as COLREP
participant ":collaborator \nCollaborator" as COL
participant ":Address" as Address

activate HRM

    HRM -> UI : Asks to register a collaborator

    activate UI

        UI --> HRM : Requests data (name, birthdate, admission date, address, \nemail,mobile number, id doc type, id doc number)
    deactivate UI

    loop until typed data is validated

    HRM -> UI : Types requested data

    activate UI
        UI --> UI : keepData(name, birthdate, admission\ndate, address, email,mobile number,\nid doc type, id doc number)
        |||
        UI -> CTRL : getJobList()


        activate CTRL

            CTRL -> RepositorySingleton : getInstance()

            activate RepositorySingleton

            RepositorySingleton --> CTRL : repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getJobRepository()
            activate PLAT

            PLAT --> CTRL : jobRepository
            deactivate PLAT

            CTRL -> JobRepository : getJobList()
            activate JobRepository

            JobRepository --> CTRL : jobList
            deactivate JobRepository

            CTRL --> UI : jobList
        deactivate CTRL

        UI --> HRM : Shows job list and asks to select one
    deactivate UI

    HRM -> UI : Selects a job

    activate UI

        UI --> UI : keepData(jobName)
        UI --> HRM : Shows all data and requests confirmation
    deactivate UI
    end

    HRM -> UI : Confirms data

    activate UI

        UI -> CTRL : createCollaborator(name, birthdate, admission\ndate, address, email,mobile number, id doc type,\nid doc number, jobName)
        activate CTRL

            CTRL -> COLREP : createCollaborator(name, birthdate, admission\ndate, address, email,mobile number, id doc type,\nid doc number, jobName)
            activate COLREP

                COLREP -> COL** : createCollaborator(name, birthdate, admission\ndate, address, email,mobile number, id doc type,\nid doc number, jobName)
                note right of COL : When creating a collaborator it uses class Email,\nAddress and Date to create the object for that attribute.

               |||
                COL -> Address** : createCreate(address)

                note right of Address: The Address object constructor is composed by:\n- street, streetNumber, postalCode, city and district
                |||
                Address --> Address : validateStreet(street)
                Address --> Address : validateStreetNumber(number)
                Address --> Address : validatePostalCode(postalCode)
                Address --> Address : validateCity(city)
                Address --> Address : validateDistrict(district)

                |||
                |||



                COL -> Email** : createEmail(email)

                Email --> Email : validateEmail(email)
                COL --> COL : validateName(name)
                COL --> COL : validateMobileNumber(mobileNumber)
                COL --> COL : validateIdDocType(idDocType)
                COL --> COL : validateIdDocNumberResults(idDocNumber, idDocType)


                |||
                |||

                COLREP -> COLREP : addToCollaboratorList(collaborator)
                COLREP --> CTRL : collaborator

            deactivate COLREP

            CTRL --> UI : collaborator
        deactivate CTRL

        UI --> HRM : Displays operation success
    deactivate UI



@enduml