@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US003 - Sequence Diagram

autonumber

actor "HRM" as HRM
participant ":RegisterCollaboratorUI" as UI
participant ":RegisterCollaboratorController" as CTRL

activate HRM

    HRM -> UI : Asks to register a collaborator

    activate UI

        UI --> HRM : Requests data (name, birthdate, admission date, address, \nemail,mobile number, id doc type, id doc number)
    deactivate UI

    HRM -> UI : Types requested data

    activate UI
        UI --> UI : keepData(name, birthdate, admission\ndate, address, email,mobile number,\nid doc type, id doc number

        UI -> CTRL : getJobList()

        activate CTRL
            CTRL -> UI : jobList
        deactivate CTRL
        UI --> HRM : Shows job list and asks to select one
    deactivate UI

    HRM -> UI : Selects a job

    activate UI

        UI --> HRM : Shows all data and requests confirmation
    deactivate UI

    HRM -> UI : Confirms data

    activate UI

        UI --> HRM : Displays operation success
    deactivate UI

@enduml