@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US009 - System Sequence Diagram (SSD)

autonumber

actor "Fleet Manager" as Employee
participant ":NeedCheckupUI" as System

activate Employee

    Employee -> System: provides waterConsumption.csv file
    activate System

        System -> System: reads and stores \nwaterConsumption.csv file
        System -> Employee: asks to select desired analysis\n (Barplot, Average Monthly costs,\n Statistical Indicators)
    deactivate System
    Employee -> System: selects Barplot
    activate System

        System -> Employee : aks for data \n(startMonth, endMonth, parkID)
    deactivate System
    Employee -> System: types data
    activate System

        System -> System: generates Barplot
        System -> Employee: shows Barplot
    deactivate System

@enduml