@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title US001 - Domain Model

class Organization {
    name
    vatNumber
    website
    phoneNumber
    email
}

class Employee {
    name
    admissionDate
    birthDate
    address
    contactInfo
    IdDocType
    IdNumber
}

class HRM{

}

class Skill{
    name
    description
}

class Collaborator{
    skills
    job
}



Organization "1" -- "*" Employee : "has >"
HRM --|> Employee
HRM "1" -- "*" Collaborator : "registers >"
HRM "1" -- "1..*" Skill : "registers >"
Collaborator "1" -- "*" Skill : "has >"

@enduml