@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US003 - System Sequence Diagram (SSD)

autonumber

actor "HRM" as Employee
participant ":RegisterCollabUI" as System

activate Employee

    Employee -> System : Asks to register a collaborator

    activate System

        System --> Employee : Requests data (name, birthdate, admission date, address, \nemail,mobile number, id doc type, id doc number)
    deactivate System

    Employee -> System : Types requested data

    activate System

        System --> Employee : Shows job list and asks to select one
    deactivate System

    Employee -> System : Selects a job

    activate System

    alt HRM wants to add one or more skills
        System --> Employee : Shows list of skills and asks to select one
    deactivate System

            loop
                Employee -> System : Selects a skill
                activate System
            end loop


        else HRM does not want to add any skills
            Employee -> System : Proceeds without adding skills
    end

        System --> Employee : Shows all data and requests confirmation
    deactivate System

    Employee -> System : Confirms data

    activate System

        System --> Employee : Displays operation success
    deactivate System

@enduml