@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US003 - System Sequence Diagram (SSD)

autonumber

actor "HRM\nMS Employee" as Employee
participant ":System" as System

activate Employee

    Employee -> System : Asks to register a colaborator

    activate System

        System --> Employee : requests data (name, birthdate, admission date, address, \nemail,mobile number, id doc type, id doc number)
    deactivate System

    Employee -> System : types requested data

    activate System

        System --> Employee : Shows job list and asks to select one
    deactivate System

    Employee -> System : Selects a job

    activate System

        System --> Employee : Shows skill list and asks to select one or more (or none)
    deactivate System

    Employee -> System : Select desired skills (0,1 or more)

    activate System

        System --> Employee : Shows all data and requests confirmation
    deactivate System

    Employee -> System : Confirms data

    activate System

        System --> Employee : Displays operation success
    deactivate System

@enduml