@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'left to right direction
skinparam classAttributeIconSize 0

hide circle
hide methods

title US011 - Domain Model


class Organization {
    name
    nif
    website
    phoneNumber
    email
}

class GreenSpace {
    name
    location
    size
    description
}

class GSM{

}

class Inquiry{
    ageRange
    recommendThePark
    visits

}

class StatisticalAnalysis{

}

Organization "1" --> "*" GreenSpace : "owns >"
GreenSpace "1" --> "*" Inquiry : "has >"
GSM "1" --> "*" StatisticalAnalysis : "lists >"
Organization "1" --> "*" StatisticalAnalysis : "analyses >"
StatisticalAnalysis "1" --> "*" Inquiry : "uses >"

@enduml