@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class RegisterVehicleUI{

}

class RegisterVehicleUIController{
    +RegisterVehicle(plate id, brand, model, type,\ntare, gross weight, current km, register date,\nacquisition date, checkup frequency kms)
}

class Repositories{
    +getInstance()
    +getVehicleRepository()
}

class VehicleRepository{
    +createVehicle(plate id, brand, model, type,\ntare, gross weight, current km, register date,\nacquisition date, checkup frequency kms)
}

class Vehicle{
    -plate id
    -brand
    -model
    -type
    -tare
    -gross weight
    -current km
    -register date
    -acquisition date
    -checkup frequency kms
    +Vehicle(plate id, brand, model, type,\ntare, gross weight, current km, register date,\nacquisition date, checkup frequency kms)
}

RegisterVehicleUI ..> RegisterVehicleUIController
RegisterVehicleUIController ..> Repositories : repositories
Repositories --> Repositories : repositories
Repositories --> "1" VehicleRepository
VehicleRepository ..> Vehicle : Vehicle

@enduml