@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US006 - System Sequence Diagram (SSD)

autonumber

actor "Fleet Manager" as Employee
participant ":RegisterVehicleUI" as System
participant ":RegisterVehicleController" as CTRL
participant ":Repositories" as REP
participant ":repositories \nRepositories" as REPS
participant ":VehicleRepository \nVehicleRepository" as VR

activate Employee

    Employee -> System : Asks to create a new vehicle
    activate System
    System->System: keepData(plate id, brand, model, type,\ntare, gross weight, current km, register date,\nacquisition date, checkup frequency kms)
    System  --> Employee : Requests vehicle data (plate id, brand, model, type,\ntare, gross weight, current km, register date,\nacquisition date, checkup frequency kms)
    deactivate System

    Employee -> System : Types requested data
    activate System

        System --> Employee : Shows all data and requests confirmation
    deactivate System

    Employee -> System : Confirms data and submits
    activate System
        System->CTRL :RegisterVehicle(plateId,brand,model,\ntype,tare,grossWeight,currentKm,\nregisterDate,acquisitionDate,\ncheckupFrequencyKms)
        activate CTRL

            CTRL->REP: getInstance()

            activate REP

            REP-->CTRL: repositories

            deactivate REP

            CTRL->REPS: getVehicleRepository()

            activate REPS

            REPS-->CTRL: VehicleRepository

            deactivate REPS

            CTRL->VR: createVehicle(plateId,brand,model,\ntype,tare,grossWeight,currentKm,\nregisterDate,acquisitionDate,\ncheckupFrequencyKms)

            activate VR

            VR->Vehicle**: createVehicle(plateId,brand,model,\ntype,tare,grossWeight,currentKm,\nregisterDate,acquisitionDate,\ncheckupFrequencyKms)

            Vehicle->Vehicle: validateVeichle(plateId, tare, currentKm, registerDate, checkupFrequencyKms)


            VR->VR: addToVehicleList(Vehicle)

            VR->VR: validateVehicle(vehicle)


            VR-->CTRL: Operation Success

            deactivate VR

            CTRL-->System: Operation success



        System --> Employee : Displays operation success
    deactivate System




@enduml