@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

'title Domain Model

class Organization {
    name
    vatNumber
    website
    phoneNumber
    email
}

class Employee {
    name
    admissionDate
    birthDate
    address
    contactInfo
    IdDocType
    IdNumber
}

class FM{

}

class Vehicle{
    plate
    brand
    model
    year
    color
}

Organization "1" --right "1..*" Employee
FM "1" --left "1" Employee : "is >"
FM "1" --down "0..*" Vehicle : "registers >"

@enduml