@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US029 - System Sequence Diagram (SSD)

autonumber
actor "Collaborator" as Collaborator
participant ":ListCollaboratorTasksUI" as UI


activate Collaborator
activate UI

loop until the collaborator shows a valid task
Collaborator -> UI: asks to record the completion of a task(selectedTask)
UI -> Collaborator: asks the confirmation of the operation
Collaborator -> UI: Confirms the operation

end loop



UI -> Collaborator: Displays operation success



@enduml