@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US026 - System Sequence Diagram (SSD)

autonumber


actor "Green Space\nManager" as GSM
participant ":AgendaUI" as UI
participant ":SelectVehiclesPopupUI" as POPUP
participant ":AgendaController" as AGENDA_CTRL

activate GSM

GSM -> UI: Asks to assign one or more vehicles to an entry in the Agenda
activate UI
UI -> AGENDA_CTRL : getAgendaTaskDTOManagerList()
    activate AGENDA_CTRL
    |||
    ref over AGENDA_CTRL
    SD_managerSpecificAgendaDTO

    end ref
    AGENDA_CTRL --> UI : managerSpecificAgendaDTO
    deactivate AGENDA_CTRL
    |||

    loop until doesn't select a valid option

    UI --> GSM: Shows the list of tasks in the agenda and asks to select one
deactivate UI

GSM -> UI : Selects a task
activate UI
UI --> UI : validates selected option
|||
end loop

    UI --> UI : keepData(task)

    UI -> POPUP : Shows the popup with the list of vehicles
    deactivate UI
    activate POPUP
    |||
    loop until doesn't choose to advance
    POPUP --> GSM: Shows the list of vehicles and asks to select the vehicles needed
deactivate POPUP

GSM -> POPUP : selects a vehicle
activate POPUP
POPUP --> POPUP : validates selected option
end loop
|||
POPUP --> UI : the list of selected vehicles to main UI
deactivate POPUP
activate UI
    |||
    UI --> UI : keepData(List<Vehicle> selectedVehicles)
    |||
    UI -> UI : adds the selected vehicles to\nthe selected entry of Agenda.
    |||


    UI --> GSM: shows operation success
deactivate UI

@enduml