@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Organization\nEmployee" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to create a new team proposal
    activate System

        System --> Employee : requests data ( max team size )
    deactivate System

    Employee -> System : types requested data

        loop
            activate System

                System --> Employee : Shows list of skills and asks to select one
            deactivate System

            Employee -> System : Selects a skill
            activate System
        end loop

        System --> Employee : shows all data and requests confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml